# Generated by Django 3.0 on 2020-10-10 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique global identifier', unique=True, verbose_name='Global ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
