# Generated by Django 3.0 on 2020-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_entities', '0006_allergen_internal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemtranslation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
