# Generated by Django 3.0 on 2020-11-16 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_entities', '0007_auto_20201103_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique global identifier', unique=True, verbose_name='Global ID')),
                ('table_code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique global identifier', unique=True, verbose_name='Global ID')),
                ('date_time', models.DateTimeField()),
                ('number_of_persons', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_entities.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
