# Generated by Django 3.0 on 2020-11-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_entities', '0010_order_ordermenuitem_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenuitem',
            name='menu_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant_entities.MenuItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant_entities.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serving',
            name='name',
            field=models.CharField(default='serving', max_length=100),
            preserve_default=False,
        ),
    ]
