# Generated by Django 3.0 on 2020-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_entities', '0011_auto_20201130_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serving',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
